const fs=require('fs');const HTML=fs.readFileSync('index.html','utf8'),CSS=fs.readFileSync('static/app.css','utf8'),JS=fs.readFileSync('static/pro.js','utf8');
let p=0,f=0;const ok=(n,c)=>c?p++:(f++,console.log('  FAIL '+n));
console.log('[1] custom picker replaces native select');
ok('native template select is gone',!HTML.includes('id="rsBotTemplate"'));
ok('clear browse trigger exists',HTML.includes('id="rsBrowseTemplates"')&&HTML.includes('Choose a starter'));
ok('picker is a real modal',HTML.includes('id="rsTemplateModal"')&&HTML.includes('id="rsTemplateGrid"'));
ok('search is available',HTML.includes('id="rsTemplateSearch"'));
ok('category rail is available',HTML.includes('id="rsTemplateCategories"'));
console.log('[2] useful card information');
ok('cards render name, description, framework and category',/t\.name/.test(JS)&&/t\.description/.test(JS)&&/t\.framework/.test(JS)&&/t\.category/.test(JS));
ok('picker filters by search',/toLowerCase\(\)\.includes\(search\)/.test(JS));
ok('picker filters by category',/_rsTemplateCategory==="All"\|\|t\.category===_rsTemplateCategory/.test(JS));
ok('selected template is reflected on trigger',/rsSelectedTemplate/.test(JS)&&/selected`/.test(JS));
ok('template strings use textContent, not card innerHTML',/card\.append\(top,desc,meta\)/.test(JS));
ok('templates can request real setup values',/rsTemplateConfigFields/.test(HTML)&&/function _renderTemplateConfig/.test(JS));
ok('required setup is validated before Continue',/_collectTemplateEnv\(true\)===null/.test(JS));
ok('setup values join the encrypted deployment env',/_collectTemplateEnv\(false\)/.test(JS)&&/BOT_TOKEN:_rsVerifiedBotToken/.test(JS));
ok('admin claim codes are generated automatically',/crypto\.getRandomValues/.test(JS)&&/field\.type==="generated"/.test(JS));
ok('claim code has a one-tap copy action',/copy\.textContent="Copy"/.test(JS)&&/navigator\.clipboard\.writeText/.test(JS));
ok('review explains exactly how admin identity is learned',/After deploy: claim admin access/.test(JS)&&/\/claim \$\{setupValues\.ADMIN_CLAIM_CODE\}/.test(JS));
ok('claim command can be copied before deployment',/Copy claim command/.test(JS));
ok('gallery advertises the full practical catalog',/20 practical bots/.test(HTML));
console.log('[3] responsive visual');
ok('desktop uses two-column cards',/\.rs-template-grid \{[^}]*grid-template-columns:1fr 1fr/.test(CSS));
ok('mobile uses one-column cards',/\.rs-template-grid\{grid-template-columns:1fr\}/.test(CSS));
ok('modal has one bounded scroll owner',/\.rs-template-modal-card \{[^}]*max-height:min\(86dvh,760px\); overflow-y:auto/.test(CSS));
ok('cards clear useful touch height',/\.rs-template-card \{[^}]*min-height:128px/.test(CSS));
console.log(`test_bot_template_picker: ${p} passed, ${f} failed`);process.exit(f?1:0);
