const fs=require('fs');
const CSS=fs.readFileSync('static/app.css','utf8');
const JS=fs.readFileSync('static/pro.js','utf8');
let pass=0,fail=0;const ok=(n,c,e)=>{if(c)pass++;else{fail++;console.log(`  FAIL ${n}${e?' -> '+e:''}`)}};
console.log('[1] composing state lifecycle');
ok('Add Bot enables the mobile composing layout',/document\.body\.classList\.add\("rs-composing"\)/.test(JS));
ok('opening a saved bot restores fixed IDE layout',/document\.body\.classList\.remove\("rs-composing"\)/.test(JS));
ok('successful deploy restores fixed IDE layout',/_composingNew = false;[^]{0,120}classList\.remove\("rs-composing"\)/.test(JS));
console.log('[2] native one-finger scroll');
ok('new-bot main pane owns vertical scrolling',/body\.rs-composing #tab-jobs \.rs-main \{[^}]*overflow-y:\s*auto/.test(CSS));
ok('native pan-y is explicitly allowed',/body\.rs-composing #tab-jobs \.rs-main \{[^}]*touch-action:\s*pan-y/.test(CSS));
ok('momentum scrolling is enabled on iOS',/-webkit-overflow-scrolling:\s*touch/.test(CSS));
ok('wizard does not trap gestures',/body\.rs-composing #tab-jobs \.rs-bot-wizard \{[^}]*touch-action:\s*pan-y/.test(CSS));
ok('CodeMirror allows native vertical pan',/body\.rs-composing #tab-jobs \.cm-scroller \{[^}]*touch-action:\s*pan-y/.test(CSS));
ok('mobile divider cannot hijack a page swipe',/if \(_composingNew && window\.innerWidth <= 760\) return/.test(JS));
ok('workspace grows into scroll content',/body\.rs-composing #tab-jobs \.rs-ws \{[^}]*overflow:\s*visible/.test(CSS));
ok('editor has a usable touch height',/body\.rs-composing #tab-jobs \.rs-split \{[^}]*min-height:\s*520px/.test(CSS));
console.log('[3] no global gesture cancellation');
const touchMoves=[...JS.matchAll(/addEventListener\("touchmove"[^]{0,500}/g)].map(x=>x[0]);
ok('touchmove handlers are passive or conditional',touchMoves.every(x=>/passive:true/.test(x)||/if \(!dragging\) return/.test(x)),String(touchMoves.length));
console.log(`test_runspace_touch_scroll: ${pass} passed, ${fail} failed`);process.exit(fail?1:0);
